server:
  port: 8081

spring:
  profiles:
    active: qa

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot-dev
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Let me welcome you in DEV!!

---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot-qa
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
welcome:
  message: Let me welcome you in QA!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot-prod
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Let me welcome you in prod!!